/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "blocks to text",
  "description": "Translate script to text",
  "tags": [],
  "credits": [
    {
      "name": "ScratchBit"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js",
    }
  ],
  "userstyles": [
    {
      "url": "style.css"
    }
  ],
  "settings": [
    {
      "id": "target",
      "name": "Only editing target",
      "default": false,
      "type": "boolean"
    }
  ],
  "dynamicDisable": true,
  "tags": [],
  "enabledByDefault": false
};
export default manifest;
