/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader!./style.css";
import _asset from "!url-loader!./icon.svg";
/*import _asset from "!url-loader!./assets/sv-gr.png";*/
export const resources = {
  "userscript.js": _js,
  "style.css": _css,
  "icon.svg": _asset,
  /*"assets/sv-gr.png": _asset,*/
};
